name: Profile Readme Development Stats

on:
  schedule:
    - cron: "30 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SECTION_NAME: waka
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LOC_CHART: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "True"
          SHOW_OS: "True"
          SHOW_LANGUAGE: "True"
          SHOW_TIMEZONE: "True"
          SHOW_COMMIT: "True"

